 


= Retours  CDCU

== Page de garde (Version, date, équipe, projet ...)
elle n'est pas présente

 
== Sommaire 
voir quand ce sera plus détaillé mais il manque déjà 
Par exemple

Une descrition de l'échancier des livrables.
Revoir le cours de gestion de projet vous avec des modèles pour le cahier des charges et pour l'évaluation des coûts.

== Objectif du projet

Il faut plus détailler.
 


Qui est le client ? Qui sont les utilisateurs de l'application ?

Pour moi deux les guichetiers et les chefs d'agences.
Il faut aussi produire un texte indiquant que les guichetiers pourront créer de nouceaux clients et faire les opétations courante...
Que les chefs d'agences pourront gérer les employé et les opérations exeptionnelles...

L'application commence par une analyse de l'exsitant puis sera découpée en plusieurs versions à la demande du client

== analyse de l'existant

 
Description du système d’information actuel de l’organisation :
Les processus informatisés ou non, impactés par le projet seront décrits
(à l’aide d’un outil de modélisation).
 ... voir docu gestion de projet
 
 Vous devriez ici avoir les UC de l'existant et vous devriez les commenter...
 
 
== les contraintes liées au projet


Vous devriez indiquer qu'il y aura un lien avec une base de donnée existante, que l'appli initiale sera fournie en java avec une IHM cpdée en java FX
Que vous devez travailler avec une équipe constituée de ...
Que les échances des différentes version du projet sont ...
...


== analyse des nouveaux besoins

 


Il faut ici que vous reformulier la demande du client afin de vous assurer que vous avez bien compris.

== La description de la solution

Un use case commenté peut être une bonne idée.
Attention bien vous avez une figure avec un titre et un numéro, il ne reste qu'à la commenter pour un client qui n'est pas un informaticien. Par exemple dire que le chef d'agence peut faire tout ce que fait u guichetier et qu'en plus il peut...

Une maquette des interfaces...

==== Modalités d’organisation pour la suite du projet

qui fait quoi ici le gant commenté c'est bien

Quels sont les dates de livraison de chaque livrable,

Quelles seront les modalités de la livraison recette, doc...



== Enveloppe  
Vous avez un doc de Mme pendaries depuis votre gantt vous avec les heures prévisionnelle de codage de test, de rédaction...
