= Cahier des charges - Version 3

== Sommaire
<<id, I. Présentation & objectifs du projet>> +
<<id, II. Analyse de l'existant>> +
<<id, III. Analyse des besoins de la version 3>> +
<<id, IV. Contraintes>> +

<<<

[[id, I. Présentation & objectifs du projet]]
=== I. Présentation & objectifs du projet

La banque Daily Bank, notre client, possède déjà une application mobile, _Daily Bank_. Or, celle-ci est assez limitée en terme de fonctionnalités et ne répond pas aux nouveaux besoins de la banque. +
Les utilisateurs de l'application sont les guichetiers et les chefs d'agence. Les premiers pourront effectuer les opérations courantes, tandis que les seconds auront en plus les opérations exceptionnelles. +
Après analyse de l'existant, la V1 et la V2 ont permis  son amélioration. Les nouvelles fonctionnalités de la V3, qui concernent le chef d'agence et le "Batch", doivent permettre de finaliser l'application pour qu'elle corresponde à la demande du client.

[[id, II. Analyse de l'existant]]
=== II. Analyse de l'existant

A l'issue de la V2, _Daily Bank_ permet : +

* Le guichetier peut modifier les informations d'un client, créer un nouveau client, consulter un compte, créditer et débiter un compte, créer un compte, effectuer un virement de compte à compte, clôturer un compte, générer un relevé mensuel d'un compte en PDF et gérer les prélèvements automatiques. +

* Le Chef d'Agence peut faire les mêmes choses que le guichetier, mais il peut également rendre inactif un client, gérer les employés, effectuer un débit exceptionnel, simuler un emprunt et simuler une assurance d'emprunt. +

[[id, III. Analyse des besoins de la version 3]]
=== III. Analyse des besoins de la version 3

Arrivés à la version 3, nous pouvons développer des fonctionnalités répondant à des besoins non exprimés mais supposés de _Daily Bank_. Nous nous pencherons dessus une fois la version 1 et 2 terminées. En effet, pour pouvoir satisfaire notre client, il faut avant tout impérativement avoir finalisé la version 1 et 2, qui elles répondent à des besoins clairement exprimés. +

Avec la version 3, nous sommes également ammené  développer un "batch", c'est-à-dire un programme autonome. Le batch répondrait au besoin d'automatisation des tâches à caractère répétitif. +

* Il génère un PDF avec les relevés mensuels

* Il exécute les prélèvements automatiques

[[id, IV. Contraintes]]
=== IV. Contraintes

Les contraintes sont : +

* L'application initiale est déjà fournie, son IHM est codée en Java FX +

* La difficulté du travail en équipe de 4 +

* Les échéances à respecter pour les différentes versions (cf. Gantt prévisionnel) +

* Le respect de la demande du client, le produit doit répondre à ses beosins
