= Daily Bank App - documentation technique V0

Nom:: documentation technique V0

Date::
08/05/2022

Nom du client:: Daily Bank

Equipe::
Mazeau Antoine <antoine.mazeau31@gmail.com> +
Benachir Alexandre <> +
Recher Olivier <recher.olivier@outlook.fr> +
Martinet Leila <leila.mrtnt1@gmail.com> +

Sommaire::
<<I. Presentation>> +
<<II. Architecture>> +
<<III. Analyse existant>> +
<<IV. Fonctionnalite>> +

'''

== Bienvenue sur Daily Bank App

[id = "I. Presentation"]
=== I. Présentation de l'application

L'application finale doit permettre de gérer les comptes bancaires des clients d'une banque. La banque Daily Bank, notre client, possède déjà une application mobile, _Daily Bank_. Or, celle-ci est assez limitée en terme de fonctionnalités et ne répond pas aux nouveaux besoins de la banque. +
Les utilisateurs de l'application sont les guichetiers et les chefs d'agence. Les premiers pourront effectuer les opérations courantes, tandis que les seconds auront en plus les opérations exceptionnelles.


[id = "II. Architecture"]
=== II. Architecture

L'application _Daily Bank_ est codée en Java 8. Les comptes ainsi que toutes leurs informations sont stockés sur une base de données. La banque doit donc prévoir un serveur où stocker sa base de données. Pour pouvoir y accéder, l'utilisateur doit se logger à la base de données via l'interface de l'application. L'IHM de l'application est en JavaFX.

[id = "III. Analyse existant"]
=== III. Analyse existant

.La V0 de Daily Bank comprend déjà les fonctionnalités suivantes :
* Pour le guichetier :
** Modifier informations client (adresse, téléphone, …)
** Créer un nouveau client
** Consulter un compte
** Débiter un compte
* Pour le chef d'agence :
** Rendre inactif un client 

+

Voici le use case que nous avons implémenté pour répondre aux nouveaux besoins de la version 1 du projet. +



* Diagramme de classes 


[id = "IV. Fonctionnalite"]
=== IV. Fonctionnalite


* Pour le guichetier :
** créer un compte bancaire
** créditer un compte bancaire
** effectuer un virement de compte à compte
** cloturer un compte
* Pour le chef d'agence :
** Gérer les employés




